### ISSUE TITLE
File looks fine on firefox and adobe reader, and compeltly balnk on atril

### ISSUE THREAD

**Issue by elyashiv** [linuxmint/mate#15]
reported [in atril project, issue 195](https://github.com/mate-desktop/atril/issues/195).

**Comment by Fred-Barclay** [comment]
Hy elyashiv. I can see the file you posted on the MATE repo fine, on LMDE Betsy MATE 64-bit. Atril version is 1.12.2. 
Apparently the atril config files are in ~/.local/share/gvfs-metadata/, though I don't know which files in that directory are for atril and which aren't. You could try recycling them (not deleting them) and then seeing if Atril now sees your document correctly.

**Comment by elyashiv** [comment]
Nope, didn't change a thing.

**Comment by Fred-Barclay** [comment]
Maybe that's to blame then. It's strange that I can see it fine with the same version of Atril you're using. 

How do other pdf's go? Can you view them?

**Comment by elyashiv** [comment]
Yes, I can.

**Comment by elyashiv** [comment]
closed in the atril project.
