### ISSUE TITLE
MATE Panel clock weather not showing

### ISSUE THREAD

**Issue by calexil** [linuxmint/mate#18]
time works fine, weather no longer shows.

probably an issue over at weather.com or wherever the weather info is sourced

issue started about a day ago, aug 23

**Comment by wubaixue** [comment]
Dito. I recall this happening occasionally in the Gnome 2 days.

**Comment by joelgsm** [comment]
It is reported in [archlinux forum](https://bbs.archlinux.org/viewtopic.php?id=216329) with this [solution](https://github.com/mate-desktop/libmateweather/commit/835055e0d0b950d3f66ad236de7e40942f6f7d8e).
Please, fix it. Thanks.

**Comment by calexil** [comment]
pull added thanks @joelgsm

**Comment by calexil** [comment]
https://github.com/linuxmint/mate/pull/19

**Comment by calexil** [comment]
@clefebvre can you confirm my merge fixes this and close it? thx

**Comment by to-ba** [comment]
@clefebvre Please update libmateweather in the repository.
Current version 1.14.0-1+sarah is not working.

**Comment by to-ba** [comment]
solution:
add: ppa:jonathonf/mate-1.14
update: libmatewheather
remove: ppa:jonathonf/mate-1.14

**Comment by calexil** [comment]
clem is merging my fix this week @to-ba
