### ISSUE TITLE
Mint menu is lagging when starting first time

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/mate#24]
I have notebook with procesor AMD A4 5000+ APU and SSD disc. 
On my notebook Mint menu is lagging when starting first time (2-3 seconds). 
Delay in start time have last for more than 5-7 seconds on slower machine! It is true.

It is important because users want have comfortable desktop for work. 
(UX - https://en.wikipedia.org/wiki/User_experience)

Menu must be load when system is loading.

**Comment by monsta** [comment]
https://github.com/linuxmint/mintmenu/issues/56
