### ISSUE TITLE
ati sensor is not found in mate sensors applet

### ISSUE THREAD

**Issue by thomastiger** [linuxmint/mate#4]
With the update of Mint 17.2 AMD64 Mate went from 1.8 to 1.10. The ATI option to display ATI/AMD GPU temperature in mate sensors applet was missing with this update. It was working with Mate 1.8.

Copying the Mate 1.8 version of aticonfig.so to /usr/lib/*/mate-sensors-applet/plugins made it work again.

Downloading the source with "apt-get source mate-sensors-applet" then compile it (./configure, make) and copy the resulting aticonfig.so to /usr/lib/*/mate-sensors-applet/plugins made it work too.

The same happened with the update from Mate 1.10.1 to 1.10.4, again download source, compile, copy aticonfig.so and it works again.

**Comment by clefebvre** [comment]
This sensor was discontinued and is no longer present.
