### ISSUE TITLE
Very slow shutdown and theme defaulting w/Steam

### ISSUE THREAD

**Issue by calexil** [linuxmint/mate#8]
as per the title, on mint 17.3 mate the system hangs on shutdown if steam is running, and the theme falls back to the default one as the system hangs for 20-30 seconds waiting for steam to exit. 

confirmed on other DE's
https://github.com/linuxmint/Cinnamon/issues/3752

**Comment by MartinX3** [comment]
+1

**Comment by calexil** [comment]
wontfix
