### ISSUE TITLE
mate-control-center scrollbar is not updated after removing search results

### ISSUE THREAD

**Issue by hiboudev** [linuxmint/mate#9]
Issue in Linux Mint 17.3 with Mate 1.12.0 (32 bits)
- How to reproduce:
  In mate-control-center, resize vertically the window to activate the vertical scrollbar, so you can use it to scroll the view.
  Do a search, for example with "net", then select all the search and delete it.
- The bug:
  All icons are now displayed, but the scrollbar did not refresh, so you can't navigate to the hidden icons.
  It seems the scrollbar refresh fine when adding text in the search box, but not when removing text.
- What is expected:
  The scrollbar should be refreshed every time the icons view is refreshed.
- How to fix it temporarily:
  Resize the window and the scrollbar is refreshed.

Note : When deleting letters one by one, sometimes scrollbar is correctly refreshed, and sometimes not.

I first opened a bug on Mate main repository : https://github.com/mate-desktop/mate-control-center/issues/216

**Comment by monsta** [comment]
This one can be closed as https://github.com/mate-desktop/mate-control-center/issues/216 is fixed.
